newBookmark("https://youtube.com", "Youtube")
newBookmark("https://music.youtube.com", "Music")
newBookmark("https://github.com", "Github")
newBookmark("https://gmail.com", "Mail")
newBookmark("https://discord.com/channels/@me", "Discord")
newBookmark("https://classroom.google.com/u/1/h", "Classroom")
newBookmark("https://keep.google.com/", "Keep")